{"uuid":"55d39c86-6420-4358-be56-34f4a1be13cc","historyId":"cec32a48146e33b2219f31b6c0f1868b","fullName":"com.automationTest.tests.BlankInputsLoginUserErrorTest.BlankInputsOnLoginPageErrorFeature","labels":[{"name":"package","value":"com.automationTest.tests.BlankInputsLoginUserErrorTest"},{"name":"testClass","value":"com.automationTest.tests.BlankInputsLoginUserErrorTest"},{"name":"testMethod","value":"BlankInputsOnLoginPageErrorFeature"},{"name":"parentSuite","value":"Suite"},{"name":"suite","value":"Test"},{"name":"subSuite","value":"com.automationTest.tests.BlankInputsLoginUserErrorTest"},{"name":"host","value":"IN-IT4609"},{"name":"thread","value":"43816@IN-IT4609.main(1)"},{"name":"severity","value":"critical"}],"links":[],"name":"BlankInputsOnLoginPageErrorFeature","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"expected [Login was unsuccessful. Please correct the errors and try again.\nThe credentials provided are incorrect] but found [Login was unsuccessful. Please correct the errors and try again.\nNo customer account found]","trace":"java.lang.AssertionError: expected [Login was unsuccessful. Please correct the errors and try again.\nThe credentials provided are incorrect] but found [Login was unsuccessful. Please correct the errors and try again.\nNo customer account found]\r\n\tat org.testng.Assert.fail(Assert.java:94)\r\n\tat org.testng.Assert.failNotEquals(Assert.java:494)\r\n\tat org.testng.Assert.assertEquals(Assert.java:123)\r\n\tat org.testng.Assert.assertEquals(Assert.java:176)\r\n\tat org.testng.Assert.assertEquals(Assert.java:186)\r\n\tat com.automationTest.pages.LoginUserBlankInputsPage.GetBlankPasswordErrorLogin(LoginUserBlankInputsPage.java:100)\r\n\tat com.automationTest.operations.BlankInputsLoginUser.BlankInputsLoginUserFeature(BlankInputsLoginUser.java:23)\r\n\tat com.automationTest.tests.BlankInputsLoginUserErrorTest.BlankInputsOnLoginPageErrorFeature(BlankInputsLoginUserErrorTest.java:32)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)\r\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:567)\r\n\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)\r\n\tat org.testng.internal.Invoker.invokeMethod(Invoker.java:714)\r\n\tat org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)\r\n\tat org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)\r\n\tat org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)\r\n\tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:767)\r\n\tat org.testng.TestRunner.run(TestRunner.java:617)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:334)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:240)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1123)\r\n\tat org.testng.TestNG.run(TestNG.java:1031)\r\n\tat org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)\r\n\tat org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)\r\n\tat org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)\r\n"},"stage":"finished","description":"Test Description: To Validate Error Message on Login Page with Blank Inputs","start":1691151527239,"stop":1691151528840,"parameters":[]}